apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: hashicorp/http-echo
        args:
        - "-text=Hello from Backend 2"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: backend2-service
spec:
  selector:
    app: backend2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  type: ClusterIP
