# nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      upstream backends {
        server backend1-service.default.svc.cluster.local;
        server backend2-service.default.svc.cluster.local;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://backends;
        }
      }
    }
